// Code generated by "stringer -type=GroqModel"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LLaMA3_8b_8192-0]
	_ = x[LLaMA3_70b_8192-1]
	_ = x[Mixtral_8x7b-2]
	_ = x[Gemma_7b-3]
	_ = x[Gemma_9b-4]
}

const _GroqModel_name = "LLaMA3_8b_8192LLaMA3_70b_8192Mixtral_8x7bGemma_7bGemma_9b"

var _GroqModel_index = [...]uint8{0, 14, 29, 41, 49, 57}

func (i GroqModel) String() string {
	if i < 0 || i >= GroqModel(len(_GroqModel_index)-1) {
		return "GroqModel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GroqModel_name[_GroqModel_index[i]:_GroqModel_index[i+1]]
}
